# Generated by Django 5.1.4 on 2026-01-17 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account_no",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Account Number"
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=255, verbose_name="Business Name"),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=255, verbose_name="Owner Name"),
                ),
                (
                    "business_location",
                    models.CharField(max_length=500, verbose_name="Business Location"),
                ),
                (
                    "rev_cat",
                    models.CharField(max_length=100, verbose_name="Revenue Category"),
                ),
                (
                    "rev_item",
                    models.CharField(max_length=100, verbose_name="Revenue Item"),
                ),
                (
                    "arrears",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Arrears",
                    ),
                ),
                (
                    "yearly_fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Yearly Fee"
                    ),
                ),
                (
                    "amt_due",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount Due"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Record",
                "verbose_name_plural": "Billing Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BopMelchia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Location"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "BOP MELCHIA",
                "verbose_name_plural": "BOP MELCHIA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyGated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "property_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Property Code"
                    ),
                ),
                (
                    "property_name",
                    models.CharField(max_length=255, verbose_name="Property Name"),
                ),
                ("location", models.CharField(max_length=500, verbose_name="Location")),
                (
                    "gate_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Gate Name"
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Property Type"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property - Gated",
                "verbose_name_plural": "Properties - Gated",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyResidential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "property_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Property Code"
                    ),
                ),
                (
                    "property_name",
                    models.CharField(max_length=255, verbose_name="Property Name"),
                ),
                ("location", models.CharField(max_length=500, verbose_name="Location")),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "property_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Property Type"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property - Residential",
                "verbose_name_plural": "Properties - Residential",
                "ordering": ["-created_at"],
            },
        ),
    ]
