# Generated by Django 5.1.4 on 2026-01-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingrecord",
            name="rev_cat",
            field=models.CharField(max_length=500, verbose_name="Revenue Category"),
        ),
        migrations.AlterField(
            model_name="billingrecord",
            name="rev_item",
            field=models.CharField(max_length=500, verbose_name="Revenue Item"),
        ),
    ]
