# Generated by Django 5.1.4 on 2026-01-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_rename_billingrecord_to_bopeasycollectible"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bopeasycollectible",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "BOP Easy Collectible",
                "verbose_name_plural": "BOP Easy Collectibles",
            },
        ),
    ]
