# Generated by Django 6.0.2 on 2026-03-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_bopeasycollectible_added_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bopmelchia',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='bopmelchia',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='bopmelchia',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='propertygated',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='propertygated',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='propertygated',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='propertyresidential',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='propertyresidential',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='propertyresidential',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='BopEasyCollectible',
        ),
        migrations.DeleteModel(
            name='BopMelchia',
        ),
        migrations.DeleteModel(
            name='PropertyGated',
        ),
        migrations.DeleteModel(
            name='PropertyResidential',
        ),
    ]
