# Generated by Django 6.0.2 on 2026-03-25 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='assessed_to_user',
            field=models.ForeignKey(blank=True, db_column='assessed_to_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='core.usermodel'),
        ),
    ]
