# Generated by Django 5.1.4 on 2026-01-27 05:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_property_geom"),
    ]

    operations = [
        migrations.CreateModel(
            name="bops",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        db_column="Account_Number",
                        max_length=100,
                        verbose_name="Account Number",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        db_column="Business_Name",
                        max_length=255,
                        verbose_name="Business Name",
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True,
                        db_column="House_Number",
                        max_length=100,
                        null=True,
                        verbose_name="House Number",
                    ),
                ),
                (
                    "digital_address",
                    models.CharField(
                        blank=True,
                        db_column="Digital_Address",
                        max_length=100,
                        null=True,
                        verbose_name="Digital Address",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=255, null=True
                    ),
                ),
                (
                    "street_name",
                    models.CharField(
                        blank=True,
                        db_column="Street_Name",
                        max_length=255,
                        null=True,
                        verbose_name="Street Name",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        db_column="Phone_Number",
                        max_length=50,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "business_email",
                    models.EmailField(
                        blank=True,
                        db_column="Business_Email",
                        max_length=255,
                        null=True,
                        verbose_name="Business Email",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, db_column="Address", null=True),
                ),
                (
                    "structure_id",
                    models.CharField(
                        blank=True,
                        db_column="Structure_ID",
                        max_length=50,
                        null=True,
                        verbose_name="Structure ID",
                    ),
                ),
                (
                    "centroid",
                    models.CharField(
                        blank=True, db_column="Centroid", max_length=100, null=True
                    ),
                ),
                (
                    "block",
                    models.CharField(
                        blank=True, db_column="Block", max_length=50, null=True
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        blank=True, db_column="Division", max_length=50, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "business_category",
                    models.TextField(
                        blank=True,
                        db_column="Business_Category",
                        null=True,
                        verbose_name="Business Category",
                    ),
                ),
                (
                    "business_class",
                    models.TextField(
                        blank=True,
                        db_column="Business_Class",
                        null=True,
                        verbose_name="Business Class",
                    ),
                ),
                (
                    "flat_rate",
                    models.DecimalField(
                        blank=True,
                        db_column="Flat_Rate",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Flat Rate",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True,
                        db_column="Owner_Name",
                        max_length=255,
                        null=True,
                        verbose_name="Owner Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_column="Email", max_length=255, null=True
                    ),
                ),
                (
                    "phone_number_primary",
                    models.CharField(
                        blank=True,
                        db_column="Phone_Number_Primary",
                        max_length=50,
                        null=True,
                        verbose_name="Phone Number Primary",
                    ),
                ),
                (
                    "source_sheet",
                    models.CharField(
                        blank=True,
                        db_column="Source_Sheet",
                        max_length=100,
                        null=True,
                        verbose_name="Source Sheet",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LANMA Business",
                "verbose_name_plural": "LANMA Businesses",
                "db_table": "lanma_businesses",
                "ordering": ["account_number"],
                "indexes": [
                    models.Index(
                        fields=["account_number"], name="lanma_busin_Account_d84a97_idx"
                    ),
                    models.Index(
                        fields=["business_name"], name="lanma_busin_Busines_fae810_idx"
                    ),
                    models.Index(
                        fields=["business_category"],
                        name="lanma_busin_Busines_145de4_idx",
                    ),
                    models.Index(
                        fields=["division"], name="lanma_busin_Divisio_9e2f29_idx"
                    ),
                ],
            },
        ),
    ]
