# Generated by Django 6.0.2 on 2026-03-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_polygon_assessed_to_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polygon',
            old_name='assessed_to_user',
            new_name='assigned_to_user',
        ),
    ]
