# Generated by Django 6.0.2 on 2026-03-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_assessed_to_user_polygon_assigned_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='passwords',
            field=models.CharField(blank=True, default='P@ssw0rd24', max_length=255, null=True),
        ),
    ]
