# Generated by Django 6.0.2 on 2026-03-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usermodel_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='passwords',
        ),
    ]
