# Generated by Django 5.1.4 on 2026-01-28 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_timestamp_fields_to_bops"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bops",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bops",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bops",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="BopsBills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bill_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated if not provided. Format: LANMA-YYYY-0001",
                        max_length=100,
                        unique=True,
                        verbose_name="Bill Number",
                    ),
                ),
                ("billing_year", models.IntegerField(verbose_name="Billing Year")),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Tax Amount"
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Penalty Amount",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Discount Amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Amount"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=100,
                        verbose_name="Status",
                    ),
                ),
                (
                    "generated_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Generated Date"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Due Date")),
                (
                    "sent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sent Date"
                    ),
                ),
                (
                    "paid_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Paid Date"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="core.bops",
                        verbose_name="Business",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Bill",
                "verbose_name_plural": "Business Bills",
                "db_table": "lanma_business_bills",
                "ordering": ["-billing_year", "-generated_date"],
                "indexes": [
                    models.Index(
                        fields=["business", "billing_year"],
                        name="lanma_busin_busines_355a0d_idx",
                    ),
                    models.Index(
                        fields=["bill_number"], name="lanma_busin_bill_nu_29349c_idx"
                    ),
                    models.Index(
                        fields=["billing_year"], name="lanma_busin_billing_f376c9_idx"
                    ),
                    models.Index(
                        fields=["status"], name="lanma_busin_status_754a5b_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="lanma_busin_due_dat_7be888_idx"
                    ),
                ],
                "unique_together": {("business", "billing_year")},
            },
        ),
    ]
