# Generated by Django 5.1.4 on 2026-01-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_bops_added_by_alter_bops_deleted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bops",
            name="lat",
            field=models.DecimalField(
                blank=True,
                db_column="Latitude",
                decimal_places=12,
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bops",
            name="lng",
            field=models.DecimalField(
                blank=True,
                db_column="Longitude",
                decimal_places=12,
                max_digits=15,
                null=True,
            ),
        ),
    ]
