# Generated by Django 6.0.2 on 2026-03-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_usermodel_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billing_year',
            field=models.IntegerField(default=0),
        ),
    ]
