# Generated by Django 6.0.2 on 2026-03-27 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bill_billing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.bopentry', verbose_name='Business'),
        ),
        migrations.AddField(
            model_name='bill',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='Number of Link Clicks'),
        ),
        migrations.AddField(
            model_name='bill',
            name='last_click_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Click IP'),
        ),
        migrations.AddField(
            model_name='bill',
            name='last_clicked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Link Clicked'),
        ),
        migrations.AddField(
            model_name='bill',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='polygon',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='addressv1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='area_in_me',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='polygon',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='elong',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='polygon',
            name='g_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='gpsname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='nlat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='polygon',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='slat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='polygon',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='wlong',
            field=models.FloatField(default=0),
        ),
    ]
