# Generated by Django 6.0.2 on 2026-02-24 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paymentprovider_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='Number of Link Clicks'),
        ),
        migrations.AddField(
            model_name='bill',
            name='last_click_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Click IP'),
        ),
        migrations.AddField(
            model_name='bill',
            name='last_clicked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Link Clicked'),
        ),
        migrations.AddField(
            model_name='bopsbills',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='Number of Link Clicks'),
        ),
        migrations.AddField(
            model_name='bopsbills',
            name='last_click_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Click IP'),
        ),
        migrations.AddField(
            model_name='bopsbills',
            name='last_clicked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Link Clicked'),
        ),
        migrations.CreateModel(
            name='PaymentLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('property', 'Property Tax'), ('business', 'Business Permit')], max_length=20)),
                ('link_type', models.CharField(choices=[('web', 'Web Link'), ('ussd', 'USSD Code'), ('qr', 'QR Code'), ('direct', 'Direct Link')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('business_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_clicks', to='core.bopsbills')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_clicks', to='core.paymenttransaction')),
                ('property_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_clicks', to='core.bill')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['bill_type', 'property_bill'], name='core_paymen_bill_ty_09731b_idx'), models.Index(fields=['bill_type', 'business_bill'], name='core_paymen_bill_ty_373e63_idx'), models.Index(fields=['clicked_at'], name='core_paymen_clicked_82e10e_idx'), models.Index(fields=['session_id'], name='core_paymen_session_2282ae_idx')],
            },
        ),
    ]
