# Generated by Django 6.0.2 on 2026-03-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bill_business_bill_click_count_bill_last_click_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('pr', 'Property Register'), ('bop', 'Business Operating Permit')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bopentry',
            name='mode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='flat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='feeschedule',
            name='bill_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentlinkclick',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('pr', 'Property Register'), ('bop', 'Business Operating Permit')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='bill_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='g_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='postcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prentry',
            name='mode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyrate',
            name='rate_code',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrate',
            name='rate_input',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True),
        ),
    ]
