# Generated by Django 6.0.2 on 2026-02-27 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bill_click_count_bill_last_click_ip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['latitude', 'longitude'], name='core_proper_latitud_67d4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['district'], name='core_proper_distric_28e832_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['zone'], name='core_proper_zone_id_59e133_idx'),
        ),
    ]
