# Generated by Django 6.0.2 on 2026-03-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bill_bill_type_alter_bopentry_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='g_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
