# Generated by Django 6.0.2 on 2026-03-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_polygon_g_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='block',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='division',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='property',
            field=models.IntegerField(default=0),
        ),
    ]
