# Generated by Django 6.0.2 on 2026-03-10 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_audittrail_audit_trail_user_id_bda44d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-id'], name='core_proper_id_112698_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['address'], name='core_proper_address_91c365_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['g_code'], name='core_proper_g_code_9f90ea_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['gpsname'], name='core_proper_gpsname_0c3d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['region'], name='core_proper_region_264d04_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['street'], name='core_proper_street_11ac6b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['addressv1'], name='core_proper_address_fd3a20_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='core_proper_created_a942a9_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='core_proper_propert_67657a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['region', 'district'], name='core_proper_region_180b02_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['zone', 'property_type'], name='core_proper_zone_id_c00ee1_idx'),
        ),
    ]
