# Generated by Django 6.0.2 on 2026-03-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_polygon_block_alter_polygon_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='block',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='division',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='property',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
