# Generated by Django 6.0.2 on 2026-03-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_polygon_block_alter_polygon_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='status',
            field=models.CharField(blank=True, choices=[('unassessed', 'Unassessed'), ('complete', 'Complete'), ('partial', 'Partial'), ('passed', 'Passed'), ('draft', 'Draft'), ('assessed', 'Assessed')], default='unassessed', max_length=20, null=True),
        ),
    ]
