# Generated by Django 6.0.2 on 2026-03-10 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_property_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['geom'], name='property_geom_idx', opclasses=['gist_geometry_ops']),
        ),
    ]
