# Generated by Django 6.0.2 on 2026-03-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_polygon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='accessed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
