# Generated by Django 6.0.2 on 2026-03-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_polygon_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bops_import_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='imported_from_bops',
            field=models.BooleanField(default=False),
        ),
    ]
