# Generated by Django 6.0.2 on 2026-03-27 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_business_bops_import_date_business_business_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.business', verbose_name='Business'),
        ),
    ]
