# Generated by Django 6.0.2 on 2026-03-27 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_bill_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('pr', 'Property Register'), ('bop', 'Business Operating Permit')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='polygon',
            field=models.ForeignKey(blank=True, db_column='polygon_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.polygon'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='session',
            field=models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.session'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
