# Generated by Django 6.0.2 on 2026-03-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_bill_amount_alter_bill_bill_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('generated', 'Generated')], default='unpaid', max_length=20, verbose_name='Status'),
        ),
    ]
