# Generated by Django 6.0.2 on 2026-03-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
