# Generated by Django 6.0.2 on 2026-03-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_bill_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('generated', 'Generated'), ('sent', 'Sent'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('partially_paid', 'Partially Paid')], default='unpaid', max_length=20, verbose_name='Status'),
        ),
    ]
