# Generated by Django 6.0.2 on 2026-03-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password_new',
            field=models.CharField(blank=True, default='P@ssw0rd24', max_length=255, null=True),
        ),
    ]
