# Generated by Django 6.0.2 on 2026-03-28 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_usermodel_password_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Chief', 'Chief'), ('None', 'None')], max_length=20, null=True)),
                ('owner_name', models.CharField(db_index=True, max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('alternative_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('ghana_card_number', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_location', models.CharField(blank=True, max_length=100, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=100, null=True)),
                ('digital_address', models.CharField(blank=True, max_length=100, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Mixed Use', 'Mixed Use'), ('Vacant Land', 'Vacant Land'), ('Other', 'Other')], max_length=50, null=True)),
                ('property_state', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Under Construction', 'Under Construction'), ('Unfinished', 'Unfinished'), ('Abandoned', 'Abandoned'), ('Under Renovation', 'Under Renovation')], max_length=50, null=True)),
                ('property_details', models.TextField(blank=True, null=True)),
                ('rooms', models.CharField(blank=True, max_length=10, null=True)),
                ('occupier', models.CharField(blank=True, choices=[('Owner Occupied', 'Owner Occupied'), ('Tenant', 'Tenant'), ('Vacant', 'Vacant'), ('Partially Occupied', 'Partially Occupied')], max_length=50, null=True)),
                ('communication_method', models.CharField(blank=True, choices=[('Phone Call', 'Phone Call'), ('SMS', 'SMS'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('In Person', 'In Person')], max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Card', 'Card')], max_length=50, null=True)),
                ('preferred_contact_time', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('collector', models.ForeignKey(blank=True, db_column='collector_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_property_owners', to='core.usermodel')),
                ('polygon', models.ForeignKey(blank=True, db_column='polygon_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_owners', to='core.polygon')),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_owners', to='core.session')),
                ('verified_by', models.ForeignKey(blank=True, db_column='verified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_property_owners', to='core.usermodel')),
            ],
            options={
                'db_table': 'property_owners',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_name'], name='property_ow_owner_n_e6eb95_idx'), models.Index(fields=['contact_number'], name='property_ow_contact_d17ea0_idx'), models.Index(fields=['polygon'], name='property_ow_polygon_de2d06_idx'), models.Index(fields=['session'], name='property_ow_session_466cc7_idx'), models.Index(fields=['created_at'], name='property_ow_created_49b288_idx')],
            },
        ),
    ]
