# Generated by Django 6.0.2 on 2026-03-28 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_propertyowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoPropertyContactAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_no_contact', models.BooleanField(default=True, help_text='Indicates that no contact is available at this property')),
                ('reason', models.CharField(blank=True, choices=[('no_one_home', 'No One Home'), ('unavailable', 'Contact Person Unavailable'), ('working_hours', 'Away During Working Hours'), ('traveling', 'Traveling/Absent'), ('business_hours', 'Business Closed'), ('after_hours', 'After Business Hours'), ('other', 'Other Reason')], help_text='Specific reason why contact is not available', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the contact attempt', null=True)),
                ('attempt_count', models.IntegerField(default=1, help_text='Number of contact attempts made')),
                ('last_attempt_at', models.DateTimeField(blank=True, help_text='Timestamp of the last contact attempt', null=True)),
                ('next_attempt_suggested', models.DateTimeField(blank=True, help_text='Suggested time for next contact attempt', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resolved', models.BooleanField(default=False, help_text='Whether this no-contact issue has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('polygon', models.ForeignKey(db_column='polygon_id', help_text='The property with no contact available', on_delete=django.db.models.deletion.CASCADE, related_name='no_contact_records', to='core.polygon')),
                ('resolved_by', models.ForeignKey(blank=True, db_column='resolved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_no_contact', to='core.usermodel')),
                ('session', models.ForeignKey(blank=True, db_column='session_id', help_text='The collection session during which contact was attempted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_contact_records', to='core.session')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', help_text='The collector who attempted to make contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_contact_records', to='core.usermodel')),
            ],
            options={
                'verbose_name': 'No Property Contact',
                'verbose_name_plural': 'No Property Contacts',
                'db_table': 'no_property_contact_available',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['polygon'], name='no_property_polygon_a9b6ea_idx'), models.Index(fields=['user'], name='no_property_user_id_fd5db9_idx'), models.Index(fields=['is_no_contact'], name='no_property_is_no_c_f4e47e_idx'), models.Index(fields=['created_at'], name='no_property_created_86c601_idx'), models.Index(fields=['resolved'], name='no_property_resolve_56246a_idx'), models.Index(fields=['session'], name='no_property_session_be8d65_idx')],
                'unique_together': {('polygon', 'is_no_contact')},
            },
        ),
        migrations.CreateModel(
            name='PassProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inaccessible', 'Property Inaccessible'), ('no_answer', 'No Answer / No Response'), ('security', 'Security Concerns'), ('vacant', 'Property Vacant'), ('under_construction', 'Under Construction'), ('wrong_address', 'Wrong Address'), ('refused', 'Owner/Resident Refused'), ('no_consent', 'No Consent to Collect Data'), ('other', 'Other Reason')], db_index=True, help_text='Reason why the property was passed', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional details about why the property was passed', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('passed_at', models.DateTimeField(auto_now_add=True, help_text='When the property was passed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, db_column='agent_id', help_text='The collector/agent who passed the property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passed_properties', to='core.usermodel')),
                ('polygon', models.ForeignKey(db_column='polygon_id', help_text='The property that was passed', on_delete=django.db.models.deletion.CASCADE, related_name='pass_records', to='core.polygon')),
                ('session', models.ForeignKey(blank=True, db_column='session_id', help_text='The collection session during which the property was passed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_records', to='core.session')),
            ],
            options={
                'verbose_name': 'Passed Property',
                'verbose_name_plural': 'Passed Properties',
                'db_table': 'pass_property',
                'ordering': ['-passed_at'],
                'indexes': [models.Index(fields=['polygon'], name='pass_proper_polygon_93ed4b_idx'), models.Index(fields=['agent'], name='pass_proper_agent_i_8423f2_idx'), models.Index(fields=['reason'], name='pass_proper_reason_a52aa5_idx'), models.Index(fields=['passed_at'], name='pass_proper_passed__b6dc5d_idx'), models.Index(fields=['session'], name='pass_proper_session_f9dd1e_idx')],
            },
        ),
    ]
